### ISSUE TITLE
cannot read Turkish radar data

### ISSUE THREAD

**Issue by adokter** [adokter/iris2odim#2]
The library throws the following error:
```
Warning: no user configuration file 'options.conf' found. Using default settings ...
Error! lowBits greater than MAX_RAY_BODY_SIZE.
lowBits = 32767; lastLowBits = 0;codeWord = -1; lastCodeWord = 0; 
ray_bytes_filled = 0; current_offset = 50.
Exiting program.
Exit from extract_rayplus with Null rayplus structure?
It usually means the program was unable to allocate a structure.
```

**Comment by adokter** [comment]
@CeciliaNilsson709 tracking your issue here

**Comment by adokter** [comment]
The error is thrown [here](https://github.com/wmo-ipet-owr/iris2odim/blob/606074e7f16459d1ee45c7049acf641bec336700/src/iris2list.c#L1286), which is in a function reading the contents of a [ray](https://github.com/wmo-ipet-owr/iris2odim/blob/606074e7f16459d1ee45c7049acf641bec336700/src/iris2list.c#L1034).

The manual of the IRIS binary format provides a lot of documentation: ftp://ftp.sigmet.com/outgoing/manuals/IRIS_Programmers_Manual.pdf

I think the issue is that the Turkish files are not IRIS RAW files, which have an extension .RAWXXXX.  Instead, many of the files have other extension, like those listed on page 130 of the manual (like .CAPXXXX, which refers to a CAPPI product). So I think we simply received many types of products, but not the product that we need (IRIS RAW).

**Comment by CeciliaNilsson709** [comment]
Ok, thank you for looking into it!
